name: Deploy to Beanstalk

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Build with maven
        run: mvn clean install -DskipTests=true -Pproduction
        
      - name: Rename jar
        run: mv target/*.jar target/prod.jar

      - name: Generate deployment package
        run: zip deploy.zip target/prod.jar Procfile

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: CelleryBackendServer
          environment_name: CelleryServer-Prod
          version_label: v${{ github.run_number }}
          region: ca-central-1
          deployment_package: deploy.zip 
    
